# Generated by Django 5.1.5 on 2025-01-31 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the disket", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, help_text="The slug of the disket", unique=True
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="The tagline of the disket. Max 160 characters.",
                        max_length=160,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="The description of the disket"),
                ),
                (
                    "tags",
                    models.CharField(
                        help_text="The tags of the disket", max_length=255
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("unlisted", "Unlisted")],
                        help_text="The visibility of the disket",
                        max_length=10,
                    ),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[("1/1", "1/1"), ("16/9", "16/9"), ("9/16", "9/16")],
                        help_text="The aspect ratio of the content.",
                        max_length=5,
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        help_text="The zip file of the disket", upload_to="uploads/"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the disket was created",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Whether the disket has been approved"
                    ),
                ),
                (
                    "content_path",
                    models.CharField(
                        blank=True,
                        help_text="The path to the content of the disket",
                        max_length=255,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
