# Generated by Django 5.1.5 on 2025-02-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disket", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disket",
            name="aspect_ratio",
        ),
        migrations.RemoveField(
            model_name="disket",
            name="description",
        ),
        migrations.RemoveField(
            model_name="disket",
            name="tags",
        ),
        migrations.AddField(
            model_name="disket",
            name="shelf",
            field=models.CharField(
                choices=[
                    ("games", "games"),
                    ("apps", "apps"),
                    ("tools", "tools"),
                    ("other", "other"),
                ],
                default="other",
                help_text="The shelf of the disket",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="disket",
            name="tagline",
            field=models.CharField(
                help_text="Short description of the disket. Max 160 characters.",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="visibility",
            field=models.CharField(
                choices=[("public", "public"), ("unlisted", "unlisted")],
                help_text="The visibility of the disket",
                max_length=10,
            ),
        ),
    ]
