# Generated by Django 5.1.5 on 2025-02-05 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "disket",
            "0002_remove_disket_aspect_ratio_remove_disket_description_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Disket",
                "verbose_name_plural": "Diskets",
            },
        ),
        migrations.RemoveField(
            model_name="disket",
            name="title",
        ),
        migrations.AddField(
            model_name="disket",
            name="label",
            field=models.CharField(
                default="foo",
                help_text="The title of the disket",
                max_length=255,
                verbose_name="Label",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="disket",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the disket has been approved",
                verbose_name="Approved",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="content_path",
            field=models.CharField(
                blank=True,
                help_text="The path to the content of the disket",
                max_length=255,
                verbose_name="Content Path",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time the disket was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="shelf",
            field=models.CharField(
                choices=[
                    ("games", "games"),
                    ("apps", "apps"),
                    ("tools", "tools"),
                    ("other", "other"),
                ],
                help_text="The shelf of the disket",
                max_length=255,
                verbose_name="Shelf",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="The slug of the disket",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="tagline",
            field=models.CharField(
                help_text="Short description of the disket. Max 160 characters.",
                max_length=160,
                verbose_name="Tagline",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="visibility",
            field=models.CharField(
                choices=[("public", "public"), ("unlisted", "unlisted")],
                help_text="The visibility of the disket",
                max_length=10,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="zip_file",
            field=models.FileField(
                help_text="The zip file of the disket",
                upload_to="uploads/",
                verbose_name="Zip File",
            ),
        ),
        migrations.CreateModel(
            name="DisketVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log",
                    models.CharField(
                        blank=True,
                        help_text="The log of the disket version",
                        max_length=255,
                        null=True,
                        verbose_name="Log",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the disket version was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "disket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disket.disket",
                        verbose_name="Disket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disket Version",
                "verbose_name_plural": "Disket Versions",
                "ordering": ["-created_at"],
            },
        ),
    ]
