# Generated by Django 5.1.6 on 2025-02-07 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disket", "0003_alter_disket_options_remove_disket_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Disket",
                "verbose_name_plural": "Disketler",
            },
        ),
        migrations.AlterModelOptions(
            name="disketversion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Disket Sürümü",
                "verbose_name_plural": "Disket Versiyonları",
            },
        ),
        migrations.RemoveField(
            model_name="disket",
            name="tagline",
        ),
        migrations.AlterField(
            model_name="disket",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="Disket onaylı mı değil mi",
                verbose_name="Onaylandı",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sahibi",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="content_path",
            field=models.CharField(
                blank=True,
                help_text="Disketin içerik yolu",
                max_length=255,
                verbose_name="İçerik Yolu",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Disketin oluşturulma tarih ve zamanı",
                verbose_name="Oluşturulma",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="label",
            field=models.CharField(
                help_text="Disketin başlığı", max_length=255, verbose_name="İsim"
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="shelf",
            field=models.CharField(
                choices=[
                    ("games", "Oyunlar"),
                    ("apps", "Uygulamalar"),
                    ("tools", "Araçlar"),
                    ("time_wasters", "Zaman Öldürücüler"),
                    ("demos", "Demolar"),
                    ("other", "Diğer"),
                ],
                help_text="Disketin durduğu raf",
                max_length=255,
                verbose_name="Raf",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Disketin takozu",
                unique=True,
                verbose_name="Kısa İsim",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="visibility",
            field=models.CharField(
                choices=[("public", "halka açık"), ("unlisted", "listelenmemiş")],
                help_text="Disketin görünürlüğü",
                max_length=10,
                verbose_name="Görünürlük",
            ),
        ),
        migrations.AlterField(
            model_name="disket",
            name="zip_file",
            field=models.FileField(
                help_text="Zip dosyası",
                upload_to="uploads/",
                verbose_name="Zip Dosyası",
            ),
        ),
        migrations.AlterField(
            model_name="disketversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Disket versiyonunun oluşturulma tarih ve zamanı",
                verbose_name="Oluşturulma",
            ),
        ),
        migrations.AlterField(
            model_name="disketversion",
            name="log",
            field=models.CharField(
                blank=True,
                help_text="Disket versiyonunun logu",
                max_length=255,
                null=True,
                verbose_name="Kayıt",
            ),
        ),
    ]
